services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:8080
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
